# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OJ Technical Notes 
email: hychen39@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Technical notes for Oracle Apex and Java Web Application developments
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hychen39.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hychen39
github_username:  hychen39
locale: "zh-TW"
# logo: "/assets/img/head-profile.jpg"
masthead_title: "OJ Technical Notes"

author:
  name     : "hychen39"
  avatar   : "/assets/img/head-profile.jpg"

# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "mint"  # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Include into processing
include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      toc: true
      toc_sticky: true
      comments: true
      share: true
      related: true
       # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

 